'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.SketchPresetColors = undefined;

var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; // Generated by CoffeeScript 0.1.6


var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _propTypes = require('prop-types');

var _propTypes2 = _interopRequireDefault(_propTypes);

var _reactcss = require('reactcss');

var _reactcss2 = _interopRequireDefault(_reactcss);

var _common = require('../common');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var SketchPresetColors = exports.SketchPresetColors = function SketchPresetColors(_ref) {
  var colors = _ref.colors,
      _ref$onClick = _ref.onClick,
      onClick = _ref$onClick === undefined ? function () {
    return {};
  } : _ref$onClick,
      onSwatchHover = _ref.onSwatchHover;

  var color, handleClick, styles, swatch, swatchWrap;
  styles = (0, _reactcss2.default)({
    default: {
      colors: {
        margin: '0 -10px',
        padding: '10px 0 0 10px',
        borderTop: '1px solid #eee',
        display: 'flex',
        flexWrap: 'wrap',
        position: 'relative'
      },
      swatchWrap: {
        width: '16px',
        height: '16px',
        margin: '0 10px 10px 0'
      },
      swatch: {
        borderRadius: '3px',
        boxShadow: 'inset 0 0 0 1px rgba(0,0,0,.15)'
      }
    },
    'no-presets': {
      colors: {
        display: 'none'
      }
    }
  }, {
    'no-presets': !(colors != null ? colors.length : void 0)
  });
  var _styles = styles;
  swatchWrap = _styles.swatchWrap;
  swatch = _styles.swatch;

  handleClick = function handleClick(hex, e) {
    return onClick({
      hex: hex,
      source: 'hex'
    }, e);
  };
  return _react2.default.createElement(
    'div',
    { className: 'flexbox-fix', style: styles.colors },
    function () {
      var i, len, results;
      results = [];
      for (i = 0, len = colors.length; i < len; i++) {
        color = colors[i];
        if (typeof color === 'string') {
          color = { color: color };
        }
        results.push(_react2.default.createElement(
          'div',
          { key: color.color, style: swatchWrap },
          _react2.default.createElement(_common.Swatch, _extends({}, color, { onClick: handleClick, onHover: onSwatchHover, focusStyle: {
              boxShadow: 'inset 0 0 0 1px rgba(0,0,0,.15), 0 0 4px ' + color.color
            }, style: swatch }))
        ));
      }
      return results;
    }()
  );
};

SketchPresetColors.propTypes = {
  colors: _propTypes2.default.arrayOf(_propTypes2.default.oneOfType([_propTypes2.default.string, _propTypes2.default.shape({
    color: _propTypes2.default.string,
    title: _propTypes2.default.string
  })]))
};

exports.default = SketchPresetColors;